Part 1
KIrillPal/Android-Mipt-Project-2024-Kondrashov pull request #2
Opened 2024-04-14 14:42 UTC by KIrillPal

2024-04-14 16:07 UTC, Ksalim01 commented
Пройдусь по пунктам из тз и сразу выставлю баллы
1. (?) нужно избавиться от использования parentFragmentManager в дочерних фрагментах, т.к. это нарушает инкапсуляцию.  
2. (0) тут нужно было какой-нибудь сплеш скрин, который бы показывался один раз
3. (0) настройка есть, но не работает
4. (0) открыл экран с чатами, перешел в ландскейп, выбросило на экран с логином
5. (3) тут все гуд 
6. (0) см. пункт 4
7. (0) не увидел
8. (0) тут, плиз, добавь иконку какую-нибудь
9. Добавь лектора в ревью

Итого: нужно поправить пункт 1 как минимум, остальное на твое усмотрение. Предлагаю решение для первого пункта
Делаешь интерфейс NavController с методами (пример): openSettingsFragment, openProfileFragment и тп. Исплементишь его либо в самом активити (простой вариант), либо в отдельном класс (можно без интерфейса, сразу класс с такими методами). Делаешь так, чтобы NavController можно было получить через активити. Во всех фрагментах через requireActivity() получаешь нужный интерфейс и работаешь с ним.  Да, и крайне рекомендую все-таки пофиксить баг в пункте 4, потому что как-то не очень откидываться на экран авторизации(
Я читал ридми btw, и даже ввиду отсутствия БД, как минимум для сплеш скрина или простеньких данных, например, того же логина и пароля, можно использовать SharedPreferences.
Также чтобы показывать какие-нибудь ошибки, на первых этапах можно использовать https://developer.android.com/guide/topics/ui/notifiers/toasts.
За ui лайк, выглядит все круто, продолжай в том же духе!

2024-04-14 16:07 UTC, Ksalim01 requested changes
Написал в комменте выше

2024-04-21 23:24 UTC, KIrillPal commented
Так, есть много изменений.

Сделан свой NavController, он сильно упростил жизнь, особенно в диплинках.
Добавил splash screen
Темной темы нет. Хочу потом сделать темную тему качественно
UI универсален и для portrait и для landscape, тестировал. Изменений нет
Добавил анимации
Восстанавливается корректно, но можно еще дополнительно потестить. Сторонних библиотек нет, Bundle есть.
Диплинки есть
a) вход: com.app.chat://login
b) регистрация: com.app.chat://signup
c) список своих чатов: com.app.chat://chatlist?login=nickname&password=password
тут используются данные для авторизации. при их неверном вводе или пропуске открывается только экран входа.
d) определенный чат: com.app.chat://chat?chatname=Top%20memes&descr=30%20участников&login=nickname&password=password
e) профиль пользователя: com.app.chat://profile?profile=Bob&info=online&status=very%20good%20person&login=nickname&password=password
Иконка и название на месте.
Жду ответа от Эмиля на приглашение.

2024-04-22 17:04 UTC, Ksalim01 commented
Пройдусь по пунктам из тз и сразу выставлю баллы
1. (4) ок
2. (0.5) ок
3. (0) оставил как было
4. (0.5) ок
5. (3) тут все гуд 
6. (2) не на каждом экране есть
7. (1.5) тут почти ок, но почему-то uri нормально не парсится когда пытаюсь открыть чаты com.app.chat://chatlist?login=nickname&password=password, пароль куда-то девается и креды не проходят
8. (0.5) ок

2024-05-04 16:14 UTC, merged